apiVersion: v1
kind: Service
metadata:
    name: webserver-endpoint
spec:
    type: ClusterIP
    ports:
      - targetPort: 80
        port: 80
    selector:
        app: webserver
        type: webserver